### ISSUE TITLE
Feature Request: reverse StringBuilder functionality

### ISSUE THREAD

**Issue by varunu28** [linkdotnet/golang-stringbuilder#4]
Languages such as Java support a reverse functionality to their StringBuilder implementation. 
https://docs.oracle.com/javase/8/docs/api/java/lang/StringBuilder.html#reverse--

For example:
```
sb.Append("a").Append("b").Reverse().ToString() -> "ba"
```

**Comment by linkdotnet** [comment]
That is a good proposal. It would be really good that the StringBuilder does that in-place and doesn't allocate new arrays.

**Comment by varunu28** [comment]
Sure. I can take a jab at it. I have an idea which can do the reversal in-place

**Comment by varunu28** [comment]
@linkdotnet Can you please assign this to me?

**Comment by linkdotnet** [comment]
@varunu28 I guess it makes more sense to add you as an contributor to the project itself - giving you direct access to push to this repository instead of your fork. 

That would make collaboration easier by a lot. What do you think?

**Comment by varunu28** [comment]
Sounds good @linkdotnet 👍

**Comment by linkdotnet** [comment]
Should be done - let me know if it works.
You should be able to directly clone the repository and push new branches to it - only pushing directly to `main` will not work.

**Comment by varunu28** [comment]
Just got the invite. Thanks for this @linkdotnet

**Comment by linkdotnet** [comment]
Thanks for jumping in and propsing cool features. Really appreciated.
